# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mp3_filename',
            field=models.CharField(default='blah', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='line_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
