# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_auto_20161021_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transcript.Document'),
        ),
    ]
