# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0003_auto_20161021_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=3)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracts', to='transcript.Document')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extract_lines', to='transcript.Extract')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.Line')),
            ],
        ),
    ]
