# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0006_extract_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='IType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'PR', b'Personal'), (b'SN', b'Sensitive'), (b'BO', b'Both')], max_length=2)),
                ('extract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.Extract')),
            ],
        ),
    ]
