# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0007_itype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itype',
            name='extract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='i_type', to='transcript.Extract'),
        ),
    ]
