# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0010_auto_20161029_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purpose',
            old_name='purposes',
            new_name='extract',
        ),
    ]
