# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0011_auto_20161029_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='extract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_purpose', to='transcript.Extract'),
        ),
    ]
