# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0012_auto_20161029_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.CharField(choices=[(b'SS', b'Sender-Subject'), (b'SR', b'Sender-Receiver'), (b'TP', b'Third-Party'), (b'FB', b'Feedback'), (b'ALL', b'All')], max_length=2)),
                ('extract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_flow', to='transcript.Extract')),
            ],
        ),
    ]
