# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0014_auto_20161029_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationflow',
            name='flow',
            field=models.CharField(choices=[(b'SS', b'Sender-Subject'), (b'SR', b'Sender-Receiver'), (b'TP', b'Third-Party'), (b'FB', b'Feedback'), (b'AL', b'All')], max_length=2),
        ),
    ]
