# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0017_placelocation_placenorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAttrRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=512)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
