# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0018_iattrref'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAttr', models.BooleanField(default=False)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.IAttrRef')),
                ('extract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.Extract')),
            ],
        ),
    ]
