# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0020_auto_20161030_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationflow',
            name='flow',
            field=models.CharField(choices=[(b'SS', b'Sender-Subject'), (b'SR', b'Sender-Receiver'), (b'TP', b'Third-Party'), (b'FB', b'Feedback'), (b'AL', b'All'), (b'NF', b'No-Flow')], max_length=2),
        ),
    ]
