# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0026_recodeextract_new_extract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recodeextract',
            name='new_extract',
        ),
    ]
