# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0027_remove_recodeextract_new_extract'),
    ]

    operations = [
        migrations.AddField(
            model_name='recodeextract',
            name='recode_context',
            field=models.CharField(default='noc', max_length=3),
            preserve_default=False,
        ),
    ]
