# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0028_recodeextract_recode_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recodeextract',
            name='extract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.Extract'),
        ),
    ]
