# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0029_auto_20161223_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractActors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=256)),
                ('context', models.CharField(max_length=15)),
                ('actor', models.CharField(default=b'', max_length=256)),
                ('conditions', models.CharField(default=b'', max_length=256)),
                ('extract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.Extract')),
            ],
        ),
    ]
