# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0030_extractactors'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractactors',
            name='data_type',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
